### PR TITLE
Update api url to new aws server in a private server

### PR DESCRIPTION
**Pull request by davidsilveira**

### CODE REVIEW

**Comment by stupied4ever** [comment]
Hi David,

can you please just write a better commit message? 
What do you mean with "wms server" ?

**Comment by davidsilveira** [comment]
Hey Rafael, 
I did a update in my commit message.
I was wrong about this "wms" the right is "aws" Sorry ;)

**Comment by stupied4ever** [comment]
David,
you ever heard about commit message best practices?
Here you can find a good post about it:
https://chris.beams.io/posts/git-commit/

If you cannot read all that right now, just follow this:

 - Separate subject from body with a blank line
 - Limit the subject line to 50 characters
 - Capitalize the subject line
 - Use the imperative mood in the subject line
 - Wrap the body at 72 characters
 - Use the body to explain what and why vs. how

Can you please ensure at least the max characters is ok?

**Comment by davidsilveira** [comment]
Thanks for this tips, I'll follow right now ;)

**Pull request closed without merging**
